// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mktmujzvugaldfvujjnb.supabase.co";
// const SUPABASE_URL = "https://mktmujzvugaldfvujjnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rdG11anp2dWdhbGRmdnVqam5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTAxMDYsImV4cCI6MjA2NjM2NjEwNn0.PHVVZzdRxAEM8_w6ORVsZxaSSlYpFlkQ4g-UveTARcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);